package com.bfsi.mfi.query;

/**
 *
 * @author Shabu
 *
 */
public final class InterfaceQuery {
	private InterfaceQuery(){}

	/*public static final String QUERY_GET_BRANCH_DATE="select branchtime from cbx_sync_time";

	public static final String CBS_QUERY_BRANCH = "SELECT BRANCH_CODE, PARENT_BRN_CODE, BRANCH_NAME, BRANCH_ADD1, BRANCH_ADD2, BRANCH_ADD3, BRANCH_ADD4," +
			" ZIP_CODE, CITY, STATE, COUNTRY, BRANCH_DATE_TODAY, BRANCH_EOD_STAT, BRANCH_LCY, RECORD_STAT FROM CBS_BRANCH_DETAIL " ;

	public static final String CBS_QUERY_CCY = "SELECT CCY_CODE, CCY_NAME, ISO_CCY_CODE, ISO_ALT_CCODE, COUNTRY, CCY_ROUND_RULE, CCY_DECIMAL, RECORD_STAT" +
			" FROM CBS_CCY_CODES ";

	public static final String CBS_QUERY_SELECT_CUST_ACC = "SELECT CUSTOMER_ID,CUST_AC_NO,BRANCH_CODE,ACCOUNT_TYPE,AC_DESC,"
			+ "AC_CCY,ACY_CURR_BAL,ACY_AVAIL_BAL,AC_STAT_NO_DR,AC_STAT_NO_CR,AC_STAT_BLOCK,AC_STAT_STOP_PAY,AC_STAT_DORMANT,"
			+ "CBS_LCR_CODE,CBS_LCR_TYPE,CBS_AGENT_CODE,JOINT_AC_INDICATOR,RECORD_STAT,CREDIT_OFFICER "
			+ " FROM CBS_CUSTOMER_ACCOUNTS";

	public static final String CBS_QUERY_CUSTOMER = "SELECT CUSTOMER_ID, PARENT_CUST_ID,"
			+ "IS_PARENT_CUST,CUSTOMER_FULL_NAME, CUSTOMER_SHORT_NAME, CUSTOMER_CATEGORY, GENDER, DOB, CUSTOMER_SINCE "
			+", ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, ZIP_CODE, CITY, STATE, "
			+ "COUNTRY, NATIONALITY, CBS_LCR_CODE,CBS_LCR_TYPE,CBS_AGENT_CODE,CBS_GROUP_CODE, LOCAL_BRANCH_CODE,  "
			+ "PREFERRED_LANGUAGE "
			+", EMAIL_ADDRESS, SMS_FROM_IBS,SMS_FROM_MBS,COLLECT_KYC, MOBILE_NUMBER, CREDIT_OFFICER, RECORD_STAT FROM CBS_CUSTOMER_DETAIL " ;

	public static final String QUERY_DEPOST = "select DEP_AC_NO,BRANCH_CODE,CUSTOMER_ID,CREDIT_OFFICER_ID,DEP_STATUS,"
			+ "AC_CCY,OPEN_DATE,MATURITY_DATE,CBS_LCR_CODE,CBS_LCR_TYPE,CBS_AGENT_CODE,SCH_INSTALLMENT_AMT,"
			+ "PAY_FREQ_TYPE,PAY_FREQ,TENURE_TYPE,TENURE,"
			+ "INT_RATE,PRINCIPAL_MATURITY_AMOUNT,INTEREST_ACCRUED_TILL_DATE,INSTALLMENT_PAID_TILL_DATE,TOTAL_INSTALLMENT_AMT_DUE,"
			+ "REDEMPTION_FLAG,REDEMPTION_PAYOUT_DATE,REDEMPTION_AMOUNT,RECORD_STAT "
			+ "from CBS_DEPOSIT_DETAIL ";
	public static final String QUERY_DEPOST_ACTIVITY = "select DEP_AC_NO,BRANCH_CODE,TXN_TYPE,TXN_TYPE_ST_DATE,TXN_TYPE_END_DATE,"
			+ "TXN_TYPE_DUE_DATE,TXN_CCY_CODE,TXN_LCY_CODE,TXN_AMT_DUE,TXN_AMT_DUE_LCY,TXN_AMT_SETTLED,TXN_AMT_SETTLED_LCY"
			+ " FROM CBS_DEPOSIT_ACTIVITY";


	public static final String CBS_QUERY_FX_RATES = "SELECT BRN_CODE, CCY1, CCY2, RECORD_STAT, MID_RATE, BUY_RATE, SALE_RATE" +
			" FROM CBS_FX_RATES ";

	public static final String CBS_QUERY_LOAN_DETAILS = "SELECT * FROM CBS_LOAN_DETAIL" ;

	public static final String CBS_QUERY_LOAN_DISBURSEMENT = "SELECT * FROM CBS_LOAN_DISBURSEMENTS" ;

	public static final String CBS_QUERY_LOAN_PAID_SCH = "SELECT * FROM CBS_LOAN_PAID_SCH " ;

	public static final String CBS_QUERY_LOAN_SCH = "SELECT * FROM CBS_LOAN_SCHEDULES" ;

*/
	public static final String QUERY_GET_BRANCH_DATE= "SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE";

	public static final String CBS_QUERY_BRANCH = "SELECT BRANCH_CODE, PARENT_BRN_CODE, BRANCH_NAME, BRANCH_ADD1, "
				+ " BRANCH_ADD2, BRANCH_ADD3, BRANCH_ADD4, ZIP_CODE, CITY, STATE, COUNTRY, BRANCH_DATE_TODAY, "
				+ " BRANCH_EOD_STAT, BRANCH_LCY, RECORD_STAT "
				+ " FROM CBX_BRANCH_DETAIL "
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";
	
	
	public static final String CBS_QUERY_CCY = "SELECT CCY_CODE, CCY_NAME, ISO_CCY_CODE, ISO_ALT_CCODE, COUNTRY, "
				+ " CCY_ROUND_RULE, CCY_DECIMAL, RECORD_STAT "
				+ " FROM CBX_CCY_CODES "
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";

	public static final String CBS_QUERY_SELECT_CUST_ACC = "SELECT CUSTOMER_ID, CUST_AC_NO, BRANCH_CODE, ACCOUNT_TYPE, "
				+ " AC_DESC,AC_CCY, ACY_CURR_BAL, ACY_AVAIL_BAL, AC_STAT_NO_DR, AC_STAT_NO_CR, AC_STAT_BLOCK, "
				+ " AC_STAT_STOP_PAY, AC_STAT_DORMANT, CBS_LCR_CODE, CBS_LCR_TYPE ,CBS_AGENT_CODE, JOINT_AC_INDICATOR, "
				+ " CREDIT_OFFICER,RECORD_STAT "
				+ " FROM CBX_CUSTOMER_ACCOUNTS "
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";

	public static final String CBS_QUERY_CUSTOMER = "SELECT CUSTOMER_ID, PARENT_CUST_ID, IS_PARENT_CUST, CUSTOMER_FULL_NAME, "
				+ " CUSTOMER_SHORT_NAME, CUSTOMER_CATEGORY, GENDER, DOB, CUSTOMER_SINCE, ADDRESS_LINE1, ADDRESS_LINE2, "
				+ " ADDRESS_LINE3, ADDRESS_LINE4, ZIP_CODE, CITY, STATE, COUNTRY, NATIONALITY, CBS_LCR_CODE, CBS_LCR_TYPE, "
				+ " CBS_AGENT_CODE, CBS_GROUP_CODE, LOCAL_BRANCH_CODE, PREFERRED_LANGUAGE, EMAIL_ADDRESS, SMS_FROM_IBS, "
				+ " SMS_FROM_MBS, COLLECT_KYC, MOBILE_NUMBER, CREDIT_OFFICER, RECORD_STAT, BUSINESS_DATE "
				+ " FROM CBX_CUSTOMER_DETAIL "
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";

	public static final String QUERY_DEPOST = " SELECT DEP_AC_NO, BRANCH_CODE, CUSTOMER_ID, CREDIT_OFFICER_ID, DEP_STATUS, "
				+ " AC_CCY ,OPEN_DATE, MATURITY_DATE, CBS_LCR_CODE, CBS_LCR_TYPE, CBS_AGENT_CODE, SCH_INSTALLMENT_AMT,  "
				+ " PAY_FREQ_TYPE, PAY_FREQ, TENURE_TYPE, TENURE, INT_RATE, PRINCIPAL_MATURITY_AMOUNT, "
				+ " INTEREST_ACCRUED_TILL_DATE, INSTALLMENT_PAID_TILL_DATE, TOTAL_INSTALLMENT_AMT_DUE, REDEMPTION_FLAG, "
				+ " REDEMPTION_PAYOUT_DATE,REDEMPTION_AMOUNT,RECORD_STAT "
				+ " FROM CBX_DEPOSIT_DETAIL "
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";

	public static final String QUERY_DEPOST_ACTIVITY = " SELECT DEP_AC_NO, BRANCH_CODE, TXN_TYPE, TXN_TYPE_ST_DATE, "
				+ " TXN_TYPE_END_DATE, TXN_TYPE_DUE_DATE, TXN_CCY_CODE, TXN_LCY_CODE, TXN_AMT_DUE, TXN_AMT_DUE_LCY, "
				+ " TXN_AMT_SETTLED, TXN_AMT_SETTLED_LCY "
				+ " FROM CBX_DEPOSIT_ACTIVITY "
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";

	public static final String CBS_QUERY_FX_RATES = " SELECT BRN_CODE, CCY1, CCY2, RECORD_STAT, MID_RATE, BUY_RATE,"
				+ " SALE_RATE"
				+ " FROM CBX_FX_RATES "
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";

	public static final String CBS_QUERY_LOAN_DETAILS =	"SELECT BRANCH_CODE, CBS_AGENT_CODE, CBS_GROUP_ID, CBS_LCR_CODE, "
				+ " CBS_LCR_TYPE, CBS_LOAN_SHORT_CODE, CREDIT_OFFICER_CODE, CUSTOMER_ID,DISBR_TYPE, DISBURSED_PRINCIPAL_AMT,"
				+ " INTEREST_ACCRUED, INTEREST_RATE, IS_FULLY_DISBURSED, IS_GROUP_LOAN, IS_PARENT_LOAN, LAST_DISBURSED_DATE,"
				+ " LAST_REPAYMENT_DATE, LOAN_AC_CCY, LOAN_AC_NO, LOAN_STATUS, PARENT_CUST_ID, PARENT_LOAN_AC_NO,"
				+ " PRINCIPAL_AMT_REPAID, PRINCIPAL_OUTSTANDING, RECORD_STAT, SANCTIONED_DATE, SANCTIONED_PRINCIPAL_AMT "
				+ " FROM CBX_LOAN_DETAIL "
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";

	public static final String CBS_QUERY_LOAN_DISBURSEMENT = " SELECT LOAN_AC_NO, BRANCH_CODE, PARENT_LOAN_AC_NO, "
				+ " CUSTOMER_ID, PARENT_CUST_ID, IS_PARENT_LOAN, IS_GROUP_LOAN, CBS_GROUP_ID, COMPONENT_NAME, DISBR_TYPE, "
				+ " SCH_ST_DATE, SCH_END_DATE, COMPONENT_CCY_CODE, COMPONENT_LCY_CODE, AMT_TO_DISBR, AMT_TO_DISBR_LCY "
				+ " FROM CBX_LOAN_DISBURSEMENTS "
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";

	public static final String CBS_QUERY_LOAN_PAID_SCH = "SELECT LOAN_AC_NO, BRANCH_CODE, PARENT_LOAN_AC_NO, CUSTOMER_ID,"
				+ " PARENT_CUST_ID, IS_PARENT_LOAN, IS_GROUP_LOAN, CBS_GROUP_ID, SCH_DUE_DATE, SCH_PAID_DATE, "
				+ "	SETTLEMENT_CCY_CODE, AMT_SETTLED, FULL_PARTIAL_IND "
				+ "	FROM CBX_LOAN_PAID_SCH"
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";

	public static final String CBS_QUERY_LOAN_SCH = "SELECT LOAN_AC_NO, BRANCH_CODE, PARENT_LOAN_AC_NO, CUSTOMER_ID, "
				+ " PARENT_CUST_ID, IS_PARENT_LOAN, IS_GROUP_LOAN, CBS_GROUP_ID, SCH_TYPE, IS_FUTURE_SCH, COMPONENT_NAME,"
				+ " SCH_ST_DATE, SCH_END_DATE, COMPONENT_CCY_CODE, COMPONENT_LCY_CODE, AMT_DUE, AMT_DUE_LCY "
				+ " FROM CBX_LOAN_SCHEDULES "
				+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";

	public static final String CBS_QUERY_CUST_ENROLL = "INSERT INTO CBX_CUST_ENROL_INFO(ENROLMENT_ID,WORKFLOW_Q_TYPE,FIRST_NAME,"
				+ " LAST_NAME,MIDDLE_NAME,DOB,GENDER,RESIDENCE_TYPE,NATIONALITY,ADDRESS1,ADDRESS2,CITY,STATE,ZIP_CODE,COUNTRY,"
				+ " EMAIL_ID,CONTACT_NO,MARTIAL_STATUS,PROFESSION,PROFESSION_REMARK,ACCOUNT_CATEGORY,ACCOUNT_TYPE,CURRENCY,"
				+ " IS_ACTIVE,MODULE_CODE,TXN_CODE,TXN_INIT_TIME,TXN_SYNC_TIME,AGENT_ID,DEVICE_ID,LOCATION_CODE,TXN_STATUS,"
				+ " TXN_ERR_CODE,TXN_ERR_MESSAGE,TEMP_GROUP_ID,IS_KYC_ONLY,CUSTOMER_ID,GROUP_INDIVIDUAL_TYPE,POC,"
				+ " ADDRESS3,ADDRESS4,INTERNAL_PROCESS_FLAG, PROCESSED_DATE_TIME, BUSINESS_DATE) "
				+ " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

	public static final String CBS_QUERY_CUST_KYC ="INSERT INTO CBX_CUST_ENROL_KYC(ENROLMENT_ID, KYC_IMAGE_CUSTOMER,"
				+ " KYC_ID_1_IMAGE, KYC_ID_1_TYPE, KYC_ID_1_NUMBER, KYC_ID_1_PROOF_TYPE, KYC_ID_2_IMAGE, KYC_ID_2_TYPE, "
				+ " KYC_ID_2_NUMBER, KYC_ID_2_PROOF_TYPE, KYC_ID_3_IMAGE, KYC_ID_3_TYPE, KYC_ID_3_NUMBER, KYC_ID_3_PROOF_TYPE) "
				+ " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

	public static final String CBS_QUERY_CUST_BIO_INFO="INSERT INTO CBX_CUST_ENROL_BIOMETRIC(ENROLMENT_ID, RHLF_TMPLTDATA, "
				+ " RHRF_TMPLTDATA, RHMF_TMPLTDATA, RHIF_TMPLTDATA, RHTF_TMPLTDATA, LHLF_TMPLTDATA, LHRF_TMPLTDATA, "
				+ " LHMF_TMPLTDATA, LHIF_TMPLTDATA, LHTF_TMPLTDATA, RHLF_IMAGE_SCAN, RHRF_IMAGE_SCAN, RHMF_IMAGE_SCAN, "
				+ " RHIF_IMAGE_SCAN, RHTF_IMAGE_SCAN, LHLF_IMAGE_SCAN, LHRF_IMAGE_SCAN,  LHMF_IMAGE_SCAN, LHIF_IMAGE_SCAN, "
				+ " LHTF_IMAGE_SCAN) "
				+ " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

	public static final String CBS_QUERY_TXNS_OUT = "INSERT INTO cbx_cbs_txn_out (MFI_OUT_SEQNO,MBS_TXN_REF_NO,MBS_TXN_SEQ_NO,CBS_AC_REF_NO,CUSTOMER_ID,CBS_BRANCH_CODE,MODULE_CODE,TXN_CODE,TXN_IDENTIFIER,SYNC_TYPE,IS_REQ_OR_TXN,"
				+ " LOG_TIME,CBS_SENT_TIME,CBS_RESPONSE_STAT,CBS_RESPONSE_TXN_REF_NO,CBS_RESPOND_TIME,CBS_ERROR_CODE,CBS_ERROR_DESC,IBS_AGENDA_ID,"
				+ " IBS_AGENDA_SEQ_NO,TXN_AMT_DUE_LCY,TXN_AMT_DUE,TXN_AMT_SETTLED_LCY,TXN_AMT_SETTLED,TXN_CCY_CODE,TXN_LCY_CODE,FULL_PARTIAL_IND,MBS_TXN_NARRATIVE,"
				+ " REQ_DEP_NO_INST,REQ_RED_REQ_DT,REQ_RED_FULL_PART_IND,REQ_MATURITY_DATE,REQ_INT_RATE,REQ_DP_TENURE_TYPE,REQ_DP_FREQUENCY_TYPE,REQ_DP_FREQUENCY,"
				+ " REQ_DP_TENURE,IS_GROUP_LOAN,IS_PARENT_LOAN,IS_PARENT_CUSTOMER,PARENT_CUSTOMER_ID,PARENT_CBS_AC_REF_NO, INTERNAL_PROCESS_FLAG, PROCESSED_DATE_TIME, BUSINESS_DATE)"
				+ " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public static final String FN_ADD_BUSINESS_DATE = "srcode.fn_get_app_date";
	
	public static final String GET_APP_DATE_TODAY = "SRCODE.FN_GET_APP_DATE" ;
	
	public static final String GET_APP_DATE_TODAYTIME = "SRCODE.FN_GET_APP_DATETIME" ;/* EGA-MN15-000007 Added Query for TimeStamp*/
	
	public static final String CBS_DROP_LIST = "SELECT BRANCH_CODE, DL_TYPE, DL_VALUE, DL_DESC FROM cbx_cbs_drop_list "
			+ " WHERE BUSINESS_DATE IN (SELECT BUSINESS_DATE FROM CBX_UPLOAD_DATE) ";
	//EGA-MN15-000015 Start
	public static final String FN_VALIDATE_CASH_TXN="fn_check_cash_txn";
	//EGA-MN15-000015 End

}
