 CREATE TABLE AMTB_AGENCYS 
   (AGENCY_CODE VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	AGENCY_DESC VARCHAR2(105 BYTE), 
	ADDRESS1 VARCHAR2(105 BYTE), 
	ADDRESS2 VARCHAR2(105 BYTE), 
	ADDRESS3 VARCHAR2(105 BYTE), 
	ADDRESS4 VARCHAR2(105 BYTE), 
	AUTH_STATUS VARCHAR2(10 BYTE) DEFAULT 'U', 
	CONTACTNUMBER VARCHAR2(20 BYTE), 
	AGENCY_STATUS VARCHAR2(20 BYTE) DEFAULT 'A', 
	PRIMARY KEY (AGENCY_CODE));


  CREATE TABLE AMTB_AGENTS 
   (AGENT_ID VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	AGENT_TYPE VARCHAR2(50 BYTE), 
	CREDIT_OFFICER VARCHAR2(50 BYTE), 
	CASH_LIMIT NUMBER, 
	DEVICE_ID VARCHAR2(100 BYTE), 
	AGENT_STATUS VARCHAR2(50 BYTE), 
	FIRST_NAME VARCHAR2(100 BYTE), 
	LAST_NAME VARCHAR2(100 BYTE), 
	DATE_OF_BIRTH TIMESTAMP (6), 
	GENDER VARCHAR2(50 BYTE), 
	COMM_ADDRESS1 VARCHAR2(100 BYTE), 
	COMM_ADDRESS2 VARCHAR2(100 BYTE), 
	COMM_ADDRESS3 VARCHAR2(100 BYTE), 
	COMM_POST_CODE VARCHAR2(100 BYTE), 
	MOBILE VARCHAR2(20 BYTE), 
	EMAIL_ID VARCHAR2(50 BYTE), 
	AGENT_START_DATE TIMESTAMP (6), 
	AGENT_END_DATE TIMESTAMP (6), 
	AGENT_LANG VARCHAR2(50 BYTE), 
	ROLE_ID VARCHAR2(50 BYTE), 
	AGENCY_CODE VARCHAR2(50 BYTE), 
	AUTH_STATUS VARCHAR2(50 BYTE) DEFAULT 'U', 
	USER_NAME VARCHAR2(100 BYTE), 
	DATA_KEY VARCHAR2(100 BYTE), 
	REG_KEY VARCHAR2(100 BYTE), 
	REG_KEY_EXPIRY_TIME TIMESTAMP (6), 
	REG_STATUS VARCHAR2(50 BYTE) DEFAULT 'U', 
	PRIMARY KEY (AGENT_ID));

 CREATE TABLE AMTB_AUDIT_DETAIL 
   (TABLE_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	KEY_ID VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	VERSION_NO NUMBER(22,0) NOT NULL ENABLE, 
	MAKER_ID VARCHAR2(25 BYTE), 
	MAKER_DT TIMESTAMP (6), 
	CHECKER_ID VARCHAR2(25 BYTE), 
	CHECKER_DT TIMESTAMP (6), 
	OBJECT_XML VARCHAR2(2108 BYTE), 
	PRIMARY KEY (TABLE_NAME, KEY_ID, VERSION_NO));


CREATE TABLE AMTB_CASH_SETTLEMENT 
   (ID VARCHAR2(25 BYTE), 
	AGENT_ID VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	CCY_CODE VARCHAR2(3 BYTE), 
	SYSTEM_POSITION NUMBER(10,0), 
	TXN_TYPE VARCHAR2(10 BYTE), 
	CASHIN_OUT VARCHAR2(10 BYTE), 
	REMARKS VARCHAR2(30 BYTE), 
	AMOUNT NUMBER, 
	TXN_TIME TIMESTAMP (6) NOT NULL ENABLE, 
	AUTH_STATUS VARCHAR2(50 BYTE), 
	PRIMARY KEY (AGENT_ID, TXN_TIME));


  CREATE TABLE AMTB_CCY_EXRATE 
   (CCY_CODE VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	FORMAT VARCHAR2(100 BYTE), 
	ISO_CCY_CODE NUMBER(22,0), 
	ISO_ALT_CCODE VARCHAR2(2 BYTE), 
	AUTH_STATUS VARCHAR2(50 BYTE), 
	PRIMARY KEY (CCY_CODE));

  CREATE TABLE AMTB_DEVICE 
   (DEVICE_ID VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	DEVICE_TYPE VARCHAR2(100 BYTE), 
	UNIQUE_ID VARCHAR2(100 BYTE), 
	ISSUED_DATE TIMESTAMP (6), 
	LAST_SYNC TIMESTAMP (6), 
	DEVICE_STATUS VARCHAR2(50 BYTE), 
	ISSUED_BY VARCHAR2(100 BYTE), 
	BRAND_MODEL VARCHAR2(100 BYTE), 
	OPERATING_SYSTEM VARCHAR2(100 BYTE), 
	APP_VERSION VARCHAR2(100 BYTE), 
	AUTH_STATUS VARCHAR2(50 BYTE) DEFAULT 'U', 
	MOBILE_NUMBER NUMBER(22,0), 
	PRIMARY KEY (DEVICE_ID));

CREATE TABLE AMTB_FUNCTION 
   (FUNC_ID VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	BASE_FUNC VARCHAR2(100 BYTE), 
	FUNC_DESC VARCHAR2(100 BYTE), 
	FUNC_COMMAND VARCHAR2(100 BYTE), 
	PRIMARY KEY (FUNC_ID));

  CREATE TABLE AMTB_LIST_VALUE 
   (LIST_NAME VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	LIST_VALUE VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	DESN VARCHAR2(200 BYTE), 
	STATUS CHAR(1 BYTE), 
	PRIMARY KEY (LIST_NAME, LIST_VALUE));

CREATE TABLE AMTB_PARAMETERS 
   (PARAM_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	PARAM_TEXT VARCHAR2(100 BYTE), 
	PARAM_TYPE VARCHAR2(100 BYTE), 
	PARAM_VALUE VARCHAR2(100 BYTE), 
	EDITABLE VARCHAR2(10 BYTE), 
	COMPONENTS VARCHAR2(100 BYTE), 
	PRIMARY KEY (PARAM_NAME));

CREATE TABLE AMTB_ROLE_ENTITLEMENT 
   (ROLE_ID VARCHAR2(25 BYTE), 
	FUNC_ID VARCHAR2(25 BYTE), 
	FOREIGN KEY (ROLE_ID) REFERENCES AMTB_ROLES (ROLE_ID) ENABLE, 
	FOREIGN KEY (FUNC_ID) REFERENCES AMTB_FUNCTION (FUNC_ID) ENABLE
	);

 CREATE TABLE AMTB_ROLES 
   (ROLE_ID VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	ROLE_NAME VARCHAR2(50 BYTE), 
	ROLE_DESC VARCHAR2(100 BYTE), 
	AUTH_STATUS VARCHAR2(50 BYTE), 
	PRIMARY KEY (ROLE_ID));


  CREATE TABLE AMTB_USER_ROLES 
   (USER_ID VARCHAR2(25 BYTE), 
	ROLE_ID VARCHAR2(50 BYTE), 
	FOREIGN KEY (USER_ID) REFERENCES AMTB_USERS (USER_ID) ENABLE
   ); 

CREATE TABLE AMTB_USERS 
   (USER_ID VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	BRANCH_CODE VARCHAR2(10 BYTE), 
	FIRST_NAME VARCHAR2(100 BYTE), 
	LAST_NAME VARCHAR2(100 BYTE), 
	DATE_OF_BIRTH TIMESTAMP (6), 
	GENDER VARCHAR2(50 BYTE), 
	COMMUNICATION_ADDRESS1 VARCHAR2(100 BYTE), 
	COMMUNICATION_ADDRESS2 VARCHAR2(100 BYTE), 
	COMMUNICATION_ADDRESS3 VARCHAR2(100 BYTE), 
	COMMUNICATION_POSTAL_CODE VARCHAR2(20 BYTE), 
	PERMANENT_ADDRESS1 VARCHAR2(100 BYTE), 
	PERMANENT_ADDRESS2 VARCHAR2(100 BYTE), 
	PERMANENT_ADDRESS3 VARCHAR2(100 BYTE), 
	PERMANENT_POSTAL_CODE VARCHAR2(20 BYTE), 
	MOBILE_NUMBER VARCHAR2(20 BYTE), 
	EMAIL_ID VARCHAR2(100 BYTE), 
	PASSWORD VARCHAR2(100 BYTE), 
	USER_TYPE VARCHAR2(50 BYTE), 
	USER_STATUS VARCHAR2(50 BYTE), 
	START_DATE TIMESTAMP (6), 
	END_DATE TIMESTAMP (6), 
	NO_OF_FAILED_LOGINS NUMBER(*,0) DEFAULT 0, 
	LAST_LOGIN_DATE TIMESTAMP (6), 
	USER_PREV_PASSWORD1 VARCHAR2(100 BYTE), 
	USER_PREV_PASSWORD2 VARCHAR2(100 BYTE), 
	AUTH_STATUS VARCHAR2(50 BYTE) DEFAULT 'U', 
	PRIMARY KEY (USER_ID));


CREATE TABLE IFTB_BRANCH_DETAILS 
   (BRANCH_CODE VARCHAR2(10 BYTE), 
	BRANCH_NAME VARCHAR2(100 BYTE), 
	BRN_ADD1 VARCHAR2(100 BYTE), 
	BRN_ADD2 VARCHAR2(100 BYTE), 
	BRN_ADD3 VARCHAR2(100 BYTE), 
	BRN_DATE TIMESTAMP (6), 
	BRN_EOD_STAT CHAR(1 BYTE), 
	BRN_LCY VARCHAR2(3 BYTE), 
	SYNC_TIME VARCHAR2(16 BYTE), 
	SYNC_STAT VARCHAR2(2 BYTE), 
	JOB_ID VARCHAR2(25 BYTE), 
	RECORD_STAT VARCHAR2(1 BYTE)
   );


CREATE TABLE IFTB_CBS_JOB_DETAIL 
   (JOB_ID VARCHAR2(50 BYTE), 
	START_TIME TIMESTAMP (6), 
	STARTED_BY VARCHAR2(100 BYTE), 
	END_TIME TIMESTAMP (6), 
	PRIMARY KEY (JOB_ID));


CREATE TABLE IFTB_CBS_JOB_HISTORY 
   (JOB_ID VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	RECORD_TYPE VARCHAR2(50 BYTE), 
	TIMESTAMP TIMESTAMP (6), 
	RECORD_ID VARCHAR2(50 BYTE), 
	OPERATION VARCHAR2(1 BYTE), 
	PRIMARY KEY (JOB_ID));

CREATE TABLE IFTB_CBS_SYNC 
   (LOAN_SYNC_TIME VARCHAR2(16 BYTE), 
	CUST_SYNC_TIME VARCHAR2(16 BYTE), 
	BRN_SYNC_TIME VARCHAR2(16 BYTE), 
	CCY_SYNC_TIME VARCHAR2(16 BYTE), 
	LOAN_SYNC CHAR(1 BYTE), 
	CUST_SYNC CHAR(1 BYTE), 
	BRN_SYNC CHAR(1 BYTE), 
	CCY_SYNC CHAR(1 BYTE), 
	FX_SYNC_TIME VARCHAR2(16 BYTE), 
	FX_SYNC VARCHAR2(2 BYTE)
   );

CREATE TABLE IFTB_CCY_DETAILS 
   (CCY_CODE VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	CCY_DESC VARCHAR2(100 BYTE), 
	ISO_ALT_CCY VARCHAR2(5 BYTE), 
	CCY_DECIMALS NUMBER, 
	RECORD_STAT VARCHAR2(2 BYTE), 
	JOB_ID VARCHAR2(25 BYTE), 
	SYNC_TIME VARCHAR2(16 BYTE), 
	SYNC_STATUS VARCHAR2(25 BYTE), 
	PRIMARY KEY (CCY_CODE));

  CREATE TABLE IFTB_CL_LIQ 
   (LOAN_AC_NO VARCHAR2(25 BYTE), 
	BRANCH_CODE VARCHAR2(5 BYTE), 
	VALUE_DATE TIMESTAMP (6), 
	EXECUTION_DATE TIMESTAMP (6), 
	PAYMENT_STATUS VARCHAR2(2 BYTE), 
	SETTLE_MODE VARCHAR2(15 BYTE), 
	SETTLE_CCY VARCHAR2(5 BYTE), 
	SETTLE_AMOUNT NUMBER(22,0), 
	EVENT_SEQ_NO NUMBER(22,0)
   );

CREATE TABLE IFTB_CLACCOUNT_SCHEDULES 
   (LOAN_AC_NO VARCHAR2(25 BYTE), 
	BRANCH_CODE VARCHAR2(5 BYTE), 
	COMPONENT_NAME VARCHAR2(25 BYTE), 
	SCHEDULE_TYPE VARCHAR2(2 BYTE), 
	SCHEDULE_ST_DATE TIMESTAMP (6), 
	SCHEDULE_DUE_DATE TIMESTAMP (6), 
	AMOUNT_DUE NUMBER, 
	ADJ_AMOUNT NUMBER, 
	AMOUNT_SETTLED NUMBER, 
	AMOUNT_OVERDUE NUMBER, 
	ACCRUED_AMOUNT NUMBER, 
	SETTLEMENT_CCY VARCHAR2(5 BYTE), 
	LCY_EQUIVALENT NUMBER
   ); 

CREATE TABLE IFTB_CUST_DETAIL 
   (CUSTOMER_ID VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	CUSTOMER_NAME VARCHAR2(100 BYTE), 
	PHONE_NUMBER VARCHAR2(15 BYTE), 
	CITY VARCHAR2(100 BYTE), 
	LOC_CODE VARCHAR2(100 BYTE), 
	LOC_NAME VARCHAR2(100 BYTE), 
	VIEW_FILE VARCHAR2(100 BYTE), 
	CREDIT_OFFICER VARCHAR2(100 BYTE), 
	SYNC_STATUS VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	SYNC_TIME VARCHAR2(16 BYTE), 
	RECORD_STAT VARCHAR2(1 BYTE), 
	ADDRESS_LINE1 VARCHAR2(100 BYTE), 
	ADDRESS_LINE2 VARCHAR2(100 BYTE), 
	UNIQUE_ID_NAME VARCHAR2(100 BYTE), 
	UNIQUE_ID_VALUE VARCHAR2(100 BYTE), 
	DOB DATE, 
	SEX VARCHAR2(100 BYTE), 
	COUNTRY VARCHAR2(100 BYTE), 
	IMAGE BLOB, 
	STATE VARCHAR2(50 BYTE), 
	JOB_ID VARCHAR2(25 BYTE), 
	PRIMARY KEY (CUSTOMER_ID));

CREATE TABLE IFTB_CUSTOMER_DOCUMENT_DATA 
   (ENROLLMENT_ID VARCHAR2(100 BYTE), 
	DOCUMENT_ID VARCHAR2(100 BYTE), 
	DOCUMENT_NAME VARCHAR2(100 BYTE), 
	DOCUMENT_TAG VARCHAR2(100 BYTE), 
	DATA BLOB, 
	PRIMARY KEY (ENROLLMENT_ID, DOCUMENT_ID));

CREATE TABLE IFTB_CUSTOMER_INFO_DATA 
   (ENROLLMENT_ID VARCHAR2(100 BYTE), 
	FIRST_NAME VARCHAR2(100 BYTE), 
	LAST_NAME VARCHAR2(100 BYTE), 
	MIDDLE_NAME VARCHAR2(100 BYTE), 
	DOB DATE, 
	GENDER VARCHAR2(100 BYTE), 
	ADDRESS1 VARCHAR2(100 BYTE), 
	ADDRESS2 VARCHAR2(100 BYTE), 
	CONTACT_NO VARCHAR2(100 BYTE), 
	EMAIL_ID VARCHAR2(100 BYTE), 
	COUNTRY VARCHAR2(100 BYTE), 
	STATE VARCHAR2(100 BYTE), 
	ZIP_CODE VARCHAR2(100 BYTE), 
	CURRENCY VARCHAR2(100 BYTE), 
	RESIDENCE_TYPE VARCHAR2(100 BYTE), 
	NATIONALITY VARCHAR2(100 BYTE), 
	MARTIAL_STATUS VARCHAR2(100 BYTE), 
	PROFESSION VARCHAR2(100 BYTE), 
	PROFESSION_REMARK VARCHAR2(100 BYTE), 
	ENROLL_DATE DATE, 
	ENRICH_STAT VARCHAR2(2 BYTE), 
	DEVICE_ID VARCHAR2(100 BYTE), 
	SYNC_TIME DATE, 
	ACCOUNT_TYPE VARCHAR2(50 BYTE), 
	ACCOUNT_TYPE_REMARK VARCHAR2(50 BYTE), 
	PRIMARY KEY (ENROLLMENT_ID));

CREATE TABLE IFTB_DISBR_SCHEDULES 
   (LOAN_AC_NO VARCHAR2(25 BYTE), 
	BRANCH_CODE VARCHAR2(5 BYTE), 
	COMPONENT_NAME VARCHAR2(25 BYTE), 
	SCHEDULE_ST_DATE TIMESTAMP (6), 
	SCHEDULE_DUE_DATE TIMESTAMP (6), 
	AMOUNT_TO_DISBR NUMBER, 
	DTYPE VARCHAR2(3 BYTE), 
	MANUAL_AMT_DISBR NUMBER, 
	CUR_DISBR_AMT NUMBER, 
	AMT_DISBURSED NUMBER, 
	MOB_TXN_ID VARCHAR2(25 BYTE)
   );


CREATE TABLE IFTB_DISBURSEMENT 
   (TXN_ID VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	TXN_NARRATIVE VARCHAR2(100 BYTE), 
	TXN_AMOUNT NUMBER(22,0), 
	TXN_CCY VARCHAR2(5 BYTE), 
	PRIMARY KEY (TXN_ID));

CREATE TABLE IFTB_ENRICHED_ENROL 
   (ENROL_CUSTADD_CODE VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	CUST_ENRICH_HOMEBRANCH VARCHAR2(255 BYTE), 
	CUST_ENRICH_CUSTCATEGORY VARCHAR2(255 BYTE), 
	CUST_ENRICH_REL_OFFICER VARCHAR2(255 BYTE)
   );


CREATE TABLE IFTB_FX_RATES 
   (CCY1 VARCHAR2(3 BYTE), 
	CCY2 VARCHAR2(3 BYTE), 
	BUY_RATE NUMBER, 
	SALE_RATE NUMBER, 
	BRN_CODE VARCHAR2(10 BYTE), 
	SYNC_TIME VARCHAR2(16 BYTE), 
	SYNC_STAT VARCHAR2(2 BYTE), 
	RECORD_STAT VARCHAR2(1 BYTE), 
	JOB_ID VARCHAR2(25 BYTE)
   );

CREATE TABLE IFTB_LOAN_DETAILS 
   (LOAN_AC_NO VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	CUSTOMER_ID VARCHAR2(15 BYTE), 
	CUSTOMER_NAME VARCHAR2(100 BYTE), 
	LOCATION_NAME VARCHAR2(100 BYTE), 
	LOCATION_ID VARCHAR2(100 BYTE), 
	NEXT_REPAYMENT_DATE TIMESTAMP (6), 
	OVERDUE_STATUS CHAR(10 BYTE), 
	LAST_DISBR_DATE TIMESTAMP (6), 
	OVER_DUE_DATE TIMESTAMP (6), 
	SANCTIONED_DATE TIMESTAMP (6), 
	GROUP_FLAG CHAR(10 BYTE), 
	GROUP_NAME VARCHAR2(100 BYTE), 
	LAST_REPAYMENT_DATE TIMESTAMP (6), 
	DISBURSEMENT_STATUS CHAR(10 BYTE), 
	GROUP_ID CHAR(10 BYTE), 
	AGENT_ID VARCHAR2(100 BYTE), 
	SYNC_STATUS VARCHAR2(25 BYTE), 
	SYNC_TIME VARCHAR2(16 BYTE), 
	ALT_ACC_NO VARCHAR2(25 BYTE), 
	LOAN_AC_CCY VARCHAR2(5 BYTE), 
	RECORD_STAT VARCHAR2(1 BYTE), 
	AMOUNT_SANCTIONED NUMBER, 
	JOB_ID VARCHAR2(25 BYTE), 
	AMOUNT_DISBURSED NUMBER, 
	PRINC_OUTSTAND NUMBER, 
	CREDIT_OFFICER VARCHAR2(50 BYTE), 
	BRANCH_CODE VARCHAR2(5 BYTE)
   ); 

CREATE TABLE IFTB_LOAN_ENRICHMENT 
   (LOAN_AC_NO VARCHAR2(25 BYTE), 
	AGENT_ID VARCHAR2(25 BYTE), 
	ALLOCATE_USER VARCHAR2(25 BYTE), 
	ALLOCATION_TIME TIMESTAMP (6), 
	PRIMARY KEY (LOAN_AC_NO));


CREATE TABLE IFTB_REPAYMENT 
   (TXN_ID VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	TXN_NARRATIVE VARCHAR2(100 BYTE), 
	TXN_AMOUNT NUMBER(22,0), 
	REPAYMENT_INST VARCHAR2(100 BYTE), 
	TXN_CCY VARCHAR2(5 BYTE), 
	PRIMARY KEY (TXN_ID));


CREATE TABLE IFTB_TRANSACTION_STATUS 
   (TXN_ID VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	SESSION_ID VARCHAR2(100 BYTE), 
	STATUS VARCHAR2(100 BYTE), 
	PRIMARY KEY (TXN_ID));

CREATE TABLE IFTB_TRANSACTIONS 
   (TXN_ID VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	TXN_TIMESTAMP TIMESTAMP (6), 
	TXN_TYPE VARCHAR2(100 BYTE), 
	AGENT_ID VARCHAR2(100 BYTE), 
	LOAN_AC_NO VARCHAR2(100 BYTE), 
	CUSTOMER_ID VARCHAR2(100 BYTE), 
	DEVICE_ID VARCHAR2(100 BYTE), 
	AUTH_STATUS VARCHAR2(100 BYTE), 
	SYNC_TIME TIMESTAMP (6), 
	TXN_STATUS VARCHAR2(100 BYTE), 
	TXN_AMOUNT NUMBER, 
	TXN_CCY VARCHAR2(100 BYTE), 
	TXN_ERROR VARCHAR2(150 BYTE), 
	BRANCH_CODE VARCHAR2(25 BYTE), 
	PRIMARY KEY (TXN_ID));


CREATE TABLE IFTW_BRANCH_DETAILS 
   (BRANCH_CODE VARCHAR2(10 BYTE), 
	BRANCH_NAME VARCHAR2(100 BYTE), 
	BRN_ADD1 VARCHAR2(100 BYTE), 
	BRN_ADD2 VARCHAR2(100 BYTE), 
	BRN_ADD3 VARCHAR2(100 BYTE), 
	BRN_ADD4 VARCHAR2(100 BYTE), 
	BRN_DATE TIMESTAMP (6), 
	BRN_EOD_STAT VARCHAR2(2 BYTE), 
	BRN_LCY VARCHAR2(5 BYTE), 
	JOB_ID VARCHAR2(25 BYTE)
   );


CREATE TABLE IFTW_CCY_DETAILS 
   (CCY_CODE VARCHAR2(5 BYTE), 
	CCY_DESC VARCHAR2(100 BYTE), 
	ISO_ALT_CCY VARCHAR2(5 BYTE), 
	CCY_DECIMALS NUMBER, 
	JOB_ID VARCHAR2(25 BYTE)
   );


CREATE TABLE IFTW_CL_LIQ 
   (LOAN_AC_NO VARCHAR2(25 BYTE), 
	BRANCH_CODE VARCHAR2(5 BYTE), 
	VALUE_DATE TIMESTAMP (6), 
	EXECUTION_DATE TIMESTAMP (6), 
	PAYMENT_STATUS VARCHAR2(2 BYTE), 
	SETTLE_MODE VARCHAR2(15 BYTE), 
	SETTLE_CCY VARCHAR2(5 BYTE), 
	SETTLE_AMOUNT NUMBER(22,0), 
	EVENT_SEQ_NO NUMBER(22,0)
   );


CREATE TABLE IFTW_CLACCOUNT_SCHEDULES 
   (LOAN_AC_NO VARCHAR2(25 BYTE), 
	BRANCH_CODE VARCHAR2(5 BYTE), 
	COMPONENT_NAME VARCHAR2(25 BYTE), 
	SCHEDULE_TYPE VARCHAR2(2 BYTE), 
	SCHEDULE_ST_DATE TIMESTAMP (6), 
	SCHEDULE_DUE_DATE TIMESTAMP (6), 
	AMOUNT_DUE NUMBER, 
	ADJ_AMOUNT NUMBER, 
	AMOUNT_SETTLED NUMBER, 
	AMOUNT_OVERDUE NUMBER, 
	ACCRUED_AMOUNT NUMBER, 
	SETTLEMENT_CCY VARCHAR2(5 BYTE), 
	LCY_EQUIVALENT NUMBER
   );


CREATE TABLE IFTW_CUST_DETAILS 
   (CUSTOMER_ID VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	CUSTOMER_NAME VARCHAR2(100 BYTE), 
	PHONE_NUMBER VARCHAR2(15 BYTE), 
	CITY VARCHAR2(100 BYTE), 
	LOC_CODE VARCHAR2(100 BYTE), 
	LOC_NAME VARCHAR2(100 BYTE), 
	VIEW_FILE VARCHAR2(100 BYTE), 
	CREDIT_OFFICER VARCHAR2(100 BYTE), 
	SYNC_STATUS VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	ADDRESS_LINE1 VARCHAR2(100 BYTE), 
	ADDRESS_LINE2 VARCHAR2(100 BYTE), 
	UNIQUE_ID_NAME VARCHAR2(100 BYTE), 
	UNIQUE_ID_VALUE VARCHAR2(100 BYTE), 
	DOB VARCHAR2(100 BYTE), 
	SEX VARCHAR2(100 BYTE), 
	COUNTRY VARCHAR2(100 BYTE), 
	IMAGE BLOB, 
	STATE VARCHAR2(50 BYTE), 
	JOB_ID VARCHAR2(25 BYTE)
   );


CREATE TABLE IFTW_DISBR_SCHEDULES 
   (LOAN_AC_NO VARCHAR2(25 BYTE), 
	BRANCH_CODE VARCHAR2(5 BYTE), 
	COMPONENT_NAME VARCHAR2(25 BYTE), 
	SCHEDULE_ST_DATE TIMESTAMP (6), 
	SCHEDULE_DUE_DATE TIMESTAMP (6), 
	AMOUNT_TO_DISBR NUMBER, 
	DTYPE VARCHAR2(3 BYTE), 
	MANUAL_AMT_DISBR NUMBER, 
	CUR_DISBR_AMT NUMBER, 
	AMT_DISBURSED NUMBER, 
	MOB_TXN_ID VARCHAR2(25 BYTE)
   );


CREATE TABLE IFTW_FX_RATES 
   (CCY1 VARCHAR2(3 BYTE), 
	CCY2 VARCHAR2(3 BYTE), 
	BUY_RATE NUMBER, 
	SALE_RATE NUMBER, 
	BRN_CODE VARCHAR2(10 BYTE), 
	JOB_ID VARCHAR2(25 BYTE)
   );


CREATE TABLE IFTW_LOAN_DETAILS 
   (LOAN_AC_NO VARCHAR2(25 BYTE) NOT NULL ENABLE, 
	CUSTOMER_ID VARCHAR2(15 BYTE), 
	CUSTOMER_NAME VARCHAR2(100 BYTE), 
	LOCATION_NAME VARCHAR2(100 BYTE), 
	LOCATION_ID VARCHAR2(100 BYTE), 
	NEXT_REPAYMENT_DATE TIMESTAMP (6), 
	OVERDUE_STATUS CHAR(10 BYTE), 
	LAST_DISBR_DATE TIMESTAMP (6), 
	OVER_DUE_DATE TIMESTAMP (6), 
	SANCTIONED_DATE TIMESTAMP (6), 
	GROUP_FLAG CHAR(10 BYTE), 
	GROUP_NAME VARCHAR2(100 BYTE), 
	LAST_REPAYMENT_DATE TIMESTAMP (6), 
	DISBURSEMENT_STATUS CHAR(10 BYTE), 
	GROUP_ID CHAR(10 BYTE), 
	AGENT_ID VARCHAR2(100 BYTE), 
	SYNC_STATUS VARCHAR2(25 BYTE), 
	ALT_ACC_NO VARCHAR2(25 BYTE), 
	LOAN_AC_CCY VARCHAR2(5 BYTE), 
	RECORD_STAT VARCHAR2(2 BYTE), 
	AMOUNT_SANCTIONED NUMBER, 
	AMOUNT_DISBURSED NUMBER, 
	PRINC_OUTSTAND NUMBER, 
	CREDIT_OFFICER VARCHAR2(50 BYTE), 
	BRANCH_CODE VARCHAR2(5 BYTE), 
	JOB_ID VARCHAR2(25 BYTE)
   );