INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00001','UserManagement','List','listUsers');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00002','UserManagement','Add','addUser');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00003','UserManagement','Modify','modifyUser');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00004','UserManagement','Delete','deleteUser');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00005','UserManagement','Authorize','authUser');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00006','RoleManagement','List','listRoles');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00007','RoleManagement','Add','addRole');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00008','RoleManagement','Modify','modifyRole');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00053','RoleManagement','Delete','deleteRole');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00010','RoleManagement','Authorize','authRole');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00011','AgentManagement','List','listAgents');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00012','AgentManagement','Add','addAgent');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00013','AgentManagement','Modify','modifyAgent');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00014','AgentManagement','Delete','deleteAgent');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00015','AgentManagement','Authorize','authAgent');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00016','DeviceManagement','List','listDevices');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00017','DeviceManagement','Add','addDevice');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00018','DeviceManagement','Modify','modifyDevice');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00019','DeviceManagement','Delete','deleteDevice');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00020','DeviceManagement','Authorize','authDevice');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00021','CashSettlement','List','listCashSettlements');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00022','CashSettlement','Add','addCashSettlement');
//INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00023','CashSettlement','Delete','deleteCashSettlement');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00024','CashSettlement','Authorize','authCashSettlement');
  
//INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00030','AgentAllocations','List','listAgentAllocations');
//INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00031','AgentAllocations','Assign','addAgentAllocations');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00032','AgentManagement','Key','generateKeyAgent');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00033','SystemParameter','List','listSystemParameters');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00034','SystemParameter','Modify','modifySystemParameter');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00035','Customers','List','listCustomers');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00036','Loan Detail','List','listLoanAccounts');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00037','Transaction Tracker','List','listAgentTxn');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00038','CBS JobHistory','List','listCbsJobHistory');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00039', 'UserManagement', 'Reset', 'resetUser');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID, BASE_FUNC, FUNC_DESC, FUNC_COMMAND) VALUES ('FUN00040', 'UserManagement','UnLock User','unLockUser');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID, BASE_FUNC, FUNC_DESC, FUNC_COMMAND) VALUES ('FUN00041', 'EnrollCustomerManagement','List','listEnrollmentCustomer');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID, BASE_FUNC, FUNC_DESC, FUNC_COMMAND) VALUES ('FUN00042', 'EnrollCustomerManagement','Enrich','enrichEnrollCustomerDetail');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00043','DisburseScheduleManagement','List','listManualDisbrSchedule');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00044','DisburseScheduleManagement','Add','addManualDisburseSchedule');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00045','DisburseScheduleManagement','Modify','modifyManualDisburseSchedule');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00046','DisburseScheduleManagement','Delete','deleteManualDisburseSchedule');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00047','DisburseScheduleManagement','Authorize','authManualDisburseSchedule');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00048','Loan Detail','Allocate Agent','addAgentAllocations');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00049','Loan Detail','Add','addManualDisburseSchedule');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00050','ListPigmyDesposit','List','listPigmyDesposit');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00052','ReferenceManagement','List','addRefCode');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00054','Micro Deposit Request','List','DepositeReqList');

INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00056', 'ReferenceManagement','Modify','modifyRefCode');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00057', 'ReferenceManagement','Authorize','authRefCode');
INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00059', 'CashSettlement','Delete','deleteCashSettlement');


INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00055','ListPigmyDesposit','AgentAllocation','allocateAgentForDeposit');
------------------------------------

//insert into IBSMFITEST.AMTB_USERS (USER_ID, BRANCH_CODE, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, GENDER, COMMUNICATION_ADDRESS1, COMMUNICATION_ADDRESS2, COMMUNICATION_ADDRESS3, COMMUNICATION_POSTAL_CODE, PERMANENT_ADDRESS1, PERMANENT_ADDRESS2, PERMANENT_ADDRESS3, PERMANENT_POSTAL_CODE, MOBILE_NUMBER, EMAIL_ID, PASSWORD, USER_TYPE, USER_STATUS, START_DATE, END_DATE, NO_OF_FAILED_LOGINS, LAST_LOGIN_DATE, USER_PREV_PASSWORD1, USER_PREV_PASSWORD2, AUTH_STATUS)
values ('admin', null, null, 'Administrator', null, '1', null, null, null, null, null, null, null, null, null, null, '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', '2', 'A', null, null, null, null, null, null, 'A');
--------------------------------------------------
INSERT INTO "IBSMFITEST"."AMTB_ROLES" (ROLE_ID,ROLE_NAME,ROLE_DESC,AUTH_STATUS) VALUES ('ROL00000','ADMINISTRATOR','Administrator of the system','A');

INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00001');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00002');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00003');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00004');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00005');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00006');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00007');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00008');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00009');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00010');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00011');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00012');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00013');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00014');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00015');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00016');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00017');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00018');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00019');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00020');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00021');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00022');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00023');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00024');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00025');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00026');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00027');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00028');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00029');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00030');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00031');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00032');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00033');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00034');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00035');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00036');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00037');
//INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00038');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00039');

//INSERT INTO "IBSMFITEST"."AMTB_USER_ROLES" (USER_ID,ROLE_ID) VALUES ('admin','ROL00000');


INSERT INTO "IBSMFITEST"."IFTB_BRANCH_DETAILS" (BRANCH_CODE,BRANCH_NAME,BRN_ADD1,BRN_ADD2,BRN_ADD3,BRN_DATE,BRN_EOD_STAT,BRN_LCY,SYNC_TIME,SYNC_STAT) VALUES ('PPP','Phnom Penh Sub Branch','Building71, St. 163, Toul Svay Prey I, Chamkamorn',null,null,to_timestamp('2013-DEC-20 00:00:00', 'RRRR-MON-DD HH24:MI:SS'),'N','KHR',to_timestamp('2014-FEB-17 17:22:27', 'RRRR-MON-DD HH24:MI:SS'),'Y');

INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('agentStatus','I','Inactive','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('agentStatus','A','Active','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('agentType','1','Credit Officer','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('agentType','2','Field Officer','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('authorize','A','Authorized','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('authorize','U','Unauthorized','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('cashInOut','1','CashIn','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('cashInOut','2','CashOut','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('deviceStatus','I','Inactive','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('deviceStatus','A','Active','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('deviceType','1','Mobile','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('deviceType','2','Tablet','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('gender','1','Male','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('gender','2','Female','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('language','1','English','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('language','2','khmer','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('paramValue','Y','Editable','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('paramValue','N','NonEditable','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('txnType','2','Sink','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('txnType','3','Adjustment','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME,LIST_VALUE,DESN,STATUS) VALUES ('txnType','1','Cash','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME, LIST_VALUE, DESN, STATUS) values ('userType','1','Credit Officer','Y');
INSERT INTO "IBSMFITEST"."AMTB_LIST_VALUE" (LIST_NAME, LIST_VALUE, DESN, STATUS) values ('userType','2','Others','Y');

insert into "IBSMFITEST"."AMTB_AUDIT_DETAIL" (table_name, key_id, version_no, maker_id, maker_dt, checker_id, checker_dt)
values ('AMTB_USERS', 'admin', 1, 'admin', SYSDATE, 'admin', SYSDATE);

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('MINIMUM PASSWORD LENGTH', 'PASSWORD', 'INTEGER', '28', 'Y', 'Mobile');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('NUMBERS OF INVALID LOGINS', 'INVALID LOGINS', 'INTEGER', '45', 'N', 'All');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DEFAULT AGENT LOGIN EXPIRY DAYS', 'EXPIRY DAYS', 'INTEGER', '3', 'y', 'All');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('MOBILE REGISTRATION KEY LENGTH', 'REGISTRATION KEY', 'INTEGER', '1', 'y', 'Mobile');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('MOBILE REGISTRATION KEY EXPIRATION TIME(IN MINUTES)', 'KEY EXPIRATION', 'INTEGER', '423', 'y', 'Mobile');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('MINIMUM MOBILE LOGIN PASSWORD LENGTH', 'MOBILE PASSWORD', 'INTEGER', '15', 'y', 'Mobile');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('MINIMUM MOBILE FAILED LOGINS', 'MOBILE FAILED LOGINS', 'INTEGER', '25', 'y', 'Mobile');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('CBS INTERFACE POLLING  ENABLED', 'POLLING  ENABLED', 'BOOLEAN', 'True', 'Y', 'All');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('CBS INTERFACE POLLING  INTERVAL IN SECONDS', 'POLLING INTERVAL', 'INTEGER', '66', 'y', 'All');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DEFAULT DEVICE SYNCH  BATCH SIZE', 'SYNCH BATCH SIZE', 'INTEGER', '5', 'y', 'All');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DAYS_FWD_DISB_AGENDA', 'DISBURSEMENT AGENDA', 'INTEGER', '7', 'Y', 'Mobile');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DAYS_FWD_REPAY_AGENDA', 'REPAYMENT AGENDA', 'INTEGER', '23', 'Y', 'Mobile');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('HOST NAME', 'HOST', 'VARCHAR', '192.168.1.112', 'Y', 'Mobile');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('NUMBERS OF RETRY', 'RETRY', 'VARCHAR', '3', 'Y', 'ALL');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DAYS SYNC', 'HOST', 'INTEGER', '3', 'Y', 'Mobile');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DEBUG', 'DEBUG', 'STRING', 'sadf', 'Y', 'All');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DEBUG_AREA', 'DEBUG_AREA', 'STRING', 'E:\MFI_APP_IBS\DB_Debug', 'Y', 'All');

insert into AMTB_PARAMETERS (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('INSUFFICIENT BALANCE OVERRIDE', 'INSUFFICIENT BALANCE', 'BOOLEAN', 'True', 'Y', 'All');


######################## Added on 12-03-3014 for unlock user and reset password (Nirmal kanna S) ########################

INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00039', 'UserManagement', 'Reset Password', 'resetUser');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00039');

INSERT INTO "IBSMFITEST"."AMTB_FUNCTION" (FUNC_ID,BASE_FUNC,FUNC_DESC,FUNC_COMMAND) VALUES ('FUN00040', 'UserManagement', 'UnLock User', 'unLockUser');
INSERT INTO "IBSMFITEST"."AMTB_ROLE_ENTITLEMENT" (ROLE_ID,FUNC_ID) VALUES ('ROL00000','FUN00040');

######################## Added on 12-03-3014 for unlock user and reset password (Nirmal kanna S) ########################

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('MINIMUM PASSWORD LENGTH', 'PASSWORD', 'INTEGER', '28', 'Y', 'Mobile');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('NUMBERS OF INVALID LOGINS', 'INVALID LOGINS', 'INTEGER', '3', 'N', 'All');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DEFAULT AGENT LOGIN EXPIRY DAYS', 'EXPIRY DAYS', 'INTEGER', '3', 'y', 'All');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('MOBILE REGISTRATION KEY LENGTH', 'REGISTRATION KEY', 'INTEGER', '1', 'y', 'Mobile');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('MOBILE REGISTRATION KEY EXPIRATION TIME(IN MINUTES)', 'KEY EXPIRATION', 'INTEGER', '423', 'y', 'Mobile');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('MINIMUM MOBILE LOGIN PASSWORD LENGTH', 'MOBILE PASSWORD', 'INTEGER', '15', 'y', 'Mobile');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('MINIMUM MOBILE FAILED LOGINS', 'MOBILE FAILED LOGINS', 'INTEGER', '25', 'y', 'Mobile');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('CBS INTERFACE POLLING  ENABLED', 'POLLING  ENABLED', 'BOOLEAN', 'True', 'Y', 'All');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('CBS INTERFACE POLLING  INTERVAL IN SECONDS', 'POLLING INTERVAL', 'INTEGER', '6', 'y', 'All');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DEFAULT DEVICE SYNCH  BATCH SIZE', 'SYNCH BATCH SIZE', 'INTEGER', '5', 'y', 'All');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DAYS_FWD_DISB_AGENDA', 'DISBURSEMENT AGENDA', 'INTEGER', '7', 'Y', 'Mobile');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DAYS_FWD_REPAY_AGENDA', 'REPAYMENT AGENDA', 'INTEGER', '23', 'Y', 'Mobile');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('HOST NAME', 'HOST', 'VARCHAR', '192.168.1.112', 'Y', 'Mobile');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('NUMBERS OF RETRY', 'RETRY', 'VARCHAR', '3', 'Y', 'ALL');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DEBUG', 'DEBUG', 'STRING', 'sadf', 'Y', 'All');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('DEBUG_AREA', 'DEBUG_AREA', 'STRING', 'E:\MFI_APP_IBS\DB_Debug', 'Y', 'All');

insert into IBSMFITEST.amtb_parameters (PARAM_NAME, PARAM_TEXT, PARAM_TYPE, PARAM_VALUE, EDITABLE, COMPONENTS)
values ('INSUFFICIENT BALANCE OVERRIDE', 'INSUFFICIENT BALANCE', 'BOOLEAN', 'True', 'Y', 'All');

INSERT INTO AMTB_USER_ROLES (USER_ID,ROLE_ID) VALUES ('su','ROL00000');

insert into AMTB_USERS (USER_ID, BRANCH_CODE, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, GENDER, COMMUNICATION_ADDRESS1, COMMUNICATION_ADDRESS2, COMMUNICATION_ADDRESS3, COMMUNICATION_POSTAL_CODE, PERMANENT_ADDRESS1, PERMANENT_ADDRESS2, PERMANENT_ADDRESS3, PERMANENT_POSTAL_CODE, MOBILE_NUMBER, EMAIL_ID, PASSWORD, USER_TYPE, USER_STATUS, START_DATE, END_DATE, NO_OF_FAILED_LOGINS, LAST_LOGIN_DATE, USER_PREV_PASSWORD1, USER_PREV_PASSWORD2, AUTH_STATUS)
values ('su', null, null, 'Administrator', null, '1', null, null, null, null, null, null, null, null, null, null, '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', '2', 'A', null, null, null, null, null, null, 'A');


insert into "IBSMFITEST"."AMTB_FUNCTION" (func_id,base_func,func_desc,func_command) values ('FUN00048','Loan Detail','Allocate Agent','addAgentAllocations');
delete from AMTB_ROLE_ENTITLEMENT where func_id in ('FUN00030','FUN00031');
delete from amtb_function where BASE_FUNC='AgentAllocations'

Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('custCategory','1','Mobile Customer','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('homeBranch','1','0001','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('homeBranch','2','0002','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('homeBranch','3','0003','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('homeBranch','4','0004','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('homeBranch','5','0005','Y');

Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('relOfficer','1','Chantou','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('relOfficer','2','Chann','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('relOfficer','3','Chakara','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('relOfficer','4','Anil','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('relOfficer','5','Marks','Y');

insert into AMTB_PARAMETERS (PARAM_NAME,PARAM_TEXT,PARAM_TYPE,PARAM_VALUE,EDITABLE,COMPONENTS) values ('TEMP HOST NAME','HOST','STRING','192.168.1.142:9090','Y','Mobile');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('customerStatus','A','Acknowleged','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('customerStatus','NA','Not Acknowleged','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('customerStatus','P','Pending','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('loanStatus','A','Acknowleged','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('loanStatus','NA','Not Acknowleged','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('loanStatus','P','Pending','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('txnStatus','A','Acknowleged','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('txnStatus','F','Fail','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('txnStatus','P','Processing ','Y');
Insert into AMTB_LIST_VALUE (LIST_NAME,LIST_VALUE,DESN,STATUS) values ('txnStatus','R','Ready For Cbs','Y');


******************************* Starts From dd/mm/2014 ******************************* 

******************************* Ends Here *******************************

******************************* Starts From dd/mm/2014 ******************************* 

******************************* Ends Here *******************************
