
package com.ofss.fcubs.gw.ws.types;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.ofss.fcubs.service.fcubsclservice.CREATEDISBURSEMENTFSFSREQ;
import com.ofss.fcubs.service.fcubsclservice.CREATEDISBURSEMENTFSFSRES;
import com.ofss.fcubs.service.fcubsclservice.CREATEDISBURSEMENTIOPKREQ;
import com.ofss.fcubs.service.fcubsclservice.CREATEDISBURSEMENTIOPKRES;
import com.ofss.fcubs.service.fcubsclservice.CREATEPAYMENTFSFSREQ;
import com.ofss.fcubs.service.fcubsclservice.CREATEPAYMENTFSFSRES;
import com.ofss.fcubs.service.fcubsclservice.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FCUBSCLServiceSEI", targetNamespace = "http://types.ws.gw.fcubs.ofss.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FCUBSCLServiceSEI {


    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CREATEACCOUNTFSFSRES
     */
   

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEACCOUNTFSFSRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.DELETEACCOUNTFSFSRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CREATEACCOUNTIOPKRES
     */
  
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.DELETEACCOUNTIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEACCOUNTIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.QUERYACCOUNTIOFSRES
     */

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.ACTIVEROLLOVERIOPKRES
     */
  
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHCLADHOCIOPKRES
     */


    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHCLUDEVENTIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHINSTSTATCHGIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHREASSIGNIOPKRES
     */
  
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHRENOGIOPKRES
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHROLLOVERIOPKRES
     */
  
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHSTATUSCHANGEIOPKRES
     */
  
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHVAMIFSFSRES
     */
  
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEACCOUNTTRFRFSFSRES
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEACCOUNTTRFRIOPKRES
     */
    
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEDISBURSEMENTFSFSRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEDISBURSEMENTIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEMORTGAGEFSFSRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEMORTGAGEIOPKRES
     */
    

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZENOTARYCONFIRMFSFSRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZENOTARYCONFIRMIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEPAYMENTFSFSRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEPAYMENTIOPKRES
     */
 
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEPRODTRFRFSFSRES
     */
  
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEPRODTRFRIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEPRODUCTFSFSRES
     */
  
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEPRODUCTIOPKRES
     */
 
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEVAMIFSFSRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.AUTHORIZEVAMIIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CLOSEACCOUNTTRFRFSFSRES
     */
  
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CLOSEACCOUNTTRFRIOPKRES
     */
 
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CLOSEPRODTRFRFSFSRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CLOSEPRODTRFRIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CREATEACCOUNTTRFRFSFSRES
     */
  
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CREATEACCOUNTTRFRIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CREATECLUDEVENTIOPKRES
     */
   
    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CREATEDISBURSEMENTFSFSRES
     */
    @WebMethod(operationName = "CreateDisbursementFS")
    @WebResult(name = "CREATEDISBURSEMENT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCLService", partName = "ResponseMsg")
    public CREATEDISBURSEMENTFSFSRES createDisbursementFS(
        @WebParam(name = "CREATEDISBURSEMENT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCLService", partName = "RequestMsg")
        CREATEDISBURSEMENTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CREATEDISBURSEMENTIOPKRES
     */
    @WebMethod(operationName = "CreateDisbursementIO")
    @WebResult(name = "CREATEDISBURSEMENT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCLService", partName = "ResponseMsg")
    public CREATEDISBURSEMENTIOPKRES createDisbursementIO(
        @WebParam(name = "CREATEDISBURSEMENT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCLService", partName = "RequestMsg")
        CREATEDISBURSEMENTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsclservice.CREATEPAYMENTFSFSRES
     */
    @WebMethod(operationName = "CreatePaymentFS")
    @WebResult(name = "CREATEPAYMENT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCLService", partName = "ResponseMsg")
    public CREATEPAYMENTFSFSRES createPaymentFS(
        @WebParam(name = "CREATEPAYMENT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSCLService", partName = "RequestMsg")
        CREATEPAYMENTFSFSREQ requestMsg);
   
}
