
package com.ofss.fcubs.gw.ws.types;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.ofss.fcubs.service.fcubsrtservice.AUTHORIZETRANSACTIONFSFSREQ;
import com.ofss.fcubs.service.fcubsrtservice.AUTHORIZETRANSACTIONFSFSRES;
import com.ofss.fcubs.service.fcubsrtservice.AUTHORIZETRANSACTIONIOPKREQ;
import com.ofss.fcubs.service.fcubsrtservice.AUTHORIZETRANSACTIONIOPKRES;
import com.ofss.fcubs.service.fcubsrtservice.CREATETRANSACTIONFSFSREQ;
import com.ofss.fcubs.service.fcubsrtservice.CREATETRANSACTIONFSFSRES;
import com.ofss.fcubs.service.fcubsrtservice.CREATETRANSACTIONIOPKREQ;
import com.ofss.fcubs.service.fcubsrtservice.CREATETRANSACTIONIOPKRES;
import com.ofss.fcubs.service.fcubsrtservice.ObjectFactory;
import com.ofss.fcubs.service.fcubsrtservice.QUERYRTPRODUCTIOFSREQ;
import com.ofss.fcubs.service.fcubsrtservice.QUERYRTPRODUCTIOFSRES;
import com.ofss.fcubs.service.fcubsrtservice.QUERYTRANSACTIONIOFSREQ;
import com.ofss.fcubs.service.fcubsrtservice.QUERYTRANSACTIONIOFSRES;
import com.ofss.fcubs.service.fcubsrtservice.REVERSETRANSACTIONFSFSREQ;
import com.ofss.fcubs.service.fcubsrtservice.REVERSETRANSACTIONFSFSRES;
import com.ofss.fcubs.service.fcubsrtservice.REVERSETRANSACTIONIOPKREQ;
import com.ofss.fcubs.service.fcubsrtservice.REVERSETRANSACTIONIOPKRES;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FCUBSRTServiceSEI", targetNamespace = "http://types.ws.gw.fcubs.ofss.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FCUBSRTServiceSEI {


    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsrtservice.AUTHORIZETRANSACTIONFSFSRES
     */
    @WebMethod(operationName = "AuthorizeTransactionFS")
    @WebResult(name = "AUTHORIZETRANSACTION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "ResponseMsg")
    public AUTHORIZETRANSACTIONFSFSRES authorizeTransactionFS(
        @WebParam(name = "AUTHORIZETRANSACTION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "RequestMsg")
        AUTHORIZETRANSACTIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsrtservice.AUTHORIZETRANSACTIONIOPKRES
     */
    @WebMethod(operationName = "AuthorizeTransactionIO")
    @WebResult(name = "AUTHORIZETRANSACTION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "ResponseMsg")
    public AUTHORIZETRANSACTIONIOPKRES authorizeTransactionIO(
        @WebParam(name = "AUTHORIZETRANSACTION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "RequestMsg")
        AUTHORIZETRANSACTIONIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsrtservice.CREATETRANSACTIONFSFSRES
     */
    @WebMethod(operationName = "CreateTransactionFS")
    @WebResult(name = "CREATETRANSACTION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "ResponseMsg")
    public CREATETRANSACTIONFSFSRES createTransactionFS(
        @WebParam(name = "CREATETRANSACTION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "RequestMsg")
        CREATETRANSACTIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsrtservice.CREATETRANSACTIONIOPKRES
     */
    @WebMethod(operationName = "CreateTransactionIO")
    @WebResult(name = "CREATETRANSACTION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "ResponseMsg")
    public CREATETRANSACTIONIOPKRES createTransactionIO(
        @WebParam(name = "CREATETRANSACTION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "RequestMsg")
        CREATETRANSACTIONIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsrtservice.QUERYRTPRODUCTIOFSRES
     */
    @WebMethod(operationName = "QueryRTProductIO")
    @WebResult(name = "QUERYRTPRODUCT_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "ResponseMsg")
    public QUERYRTPRODUCTIOFSRES queryRTProductIO(
        @WebParam(name = "QUERYRTPRODUCT_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "RequestMsg")
        QUERYRTPRODUCTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsrtservice.QUERYTRANSACTIONIOFSRES
     */
    @WebMethod(operationName = "QueryTransactionIO")
    @WebResult(name = "QUERYTRANSACTION_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "ResponseMsg")
    public QUERYTRANSACTIONIOFSRES queryTransactionIO(
        @WebParam(name = "QUERYTRANSACTION_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "RequestMsg")
        QUERYTRANSACTIONIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsrtservice.REVERSETRANSACTIONFSFSRES
     */
    @WebMethod(operationName = "ReverseTransactionFS")
    @WebResult(name = "REVERSETRANSACTION_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "ResponseMsg")
    public REVERSETRANSACTIONFSFSRES reverseTransactionFS(
        @WebParam(name = "REVERSETRANSACTION_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "RequestMsg")
        REVERSETRANSACTIONFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.ofss.fcubs.service.fcubsrtservice.REVERSETRANSACTIONIOPKRES
     */
    @WebMethod(operationName = "ReverseTransactionIO")
    @WebResult(name = "REVERSETRANSACTION_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "ResponseMsg")
    public REVERSETRANSACTIONIOPKRES reverseTransactionIO(
        @WebParam(name = "REVERSETRANSACTION_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSRTService", partName = "RequestMsg")
        REVERSETRANSACTIONIOPKREQ requestMsg);

}
